// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IcyOptions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from IcyOptions.proto</summary>
public static partial class IcyOptionsReflection {

  #region Descriptor
  /// <summary>File descriptor for IcyOptions.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static IcyOptionsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBJY3lPcHRpb25zLnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRv",
          "ci5wcm90bzozCgVNc2dJRBIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0",
          "aW9ucxjQhgMgASgFiAEBYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { IcyOptionsExtensions.MsgID }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of IcyOptions.proto</summary>
public static partial class IcyOptionsExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int> MsgID =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int>(50000, pb::FieldCodec.ForInt32(400000, 0));
}


#endregion Designer generated code
