// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoOptions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProtoOptions.proto</summary>
public static partial class ProtoOptionsReflection {

  #region Descriptor
  /// <summary>File descriptor for ProtoOptions.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtoOptionsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJQcm90b09wdGlvbnMucHJvdG8aIGdvb2dsZS9wcm90b2J1Zi9kZXNjcmlw",
          "dG9yLnByb3RvOjMKBU1zZ0lEEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VP",
          "cHRpb25zGNCGAyABKAWIAQFiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { ProtoOptionsExtensions.MsgID }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of ProtoOptions.proto</summary>
public static partial class ProtoOptionsExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int> MsgID =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int>(50000, pb::FieldCodec.ForInt32(400000, 0));
}


#endregion Designer generated code
