// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigSetting.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Icy.Editor {

  /// <summary>Holder for reflection information generated from ConfigSetting.proto</summary>
  public static partial class ConfigSettingReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigSetting.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigSettingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNDb25maWdTZXR0aW5nLnByb3RvEgpJY3kuRWRpdG9yImwKDUNvbmZpZ1Nl",
            "dHRpbmcSFwoPR2VuZXJhdGVCYXRQYXRoGAEgASgJEhUKDUNvZGVPdXRwdXRE",
            "aXIYAiABKAkSFAoMQmluT3V0cHV0RGlyGAMgASgJEhUKDUpzb25PdXRwdXRE",
            "aXIYBCABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Icy.Editor.ConfigSetting), global::Icy.Editor.ConfigSetting.Parser, new[]{ "GenerateBatPath", "CodeOutputDir", "BinOutputDir", "JsonOutputDir" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ConfigSetting : pb::IMessage<ConfigSetting>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConfigSetting> _parser = new pb::MessageParser<ConfigSetting>(() => new ConfigSetting());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConfigSetting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Icy.Editor.ConfigSettingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigSetting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigSetting(ConfigSetting other) : this() {
      generateBatPath_ = other.generateBatPath_;
      codeOutputDir_ = other.codeOutputDir_;
      binOutputDir_ = other.binOutputDir_;
      jsonOutputDir_ = other.jsonOutputDir_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigSetting Clone() {
      return new ConfigSetting(this);
    }

    /// <summary>Field number for the "GenerateBatPath" field.</summary>
    public const int GenerateBatPathFieldNumber = 1;
    private string generateBatPath_ = "";
    /// <summary>
    ///生成Config的Bat脚本路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GenerateBatPath {
      get { return generateBatPath_; }
      set {
        generateBatPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CodeOutputDir" field.</summary>
    public const int CodeOutputDirFieldNumber = 2;
    private string codeOutputDir_ = "";
    /// <summary>
    ///Config代码的导出输出目录
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CodeOutputDir {
      get { return codeOutputDir_; }
      set {
        codeOutputDir_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BinOutputDir" field.</summary>
    public const int BinOutputDirFieldNumber = 3;
    private string binOutputDir_ = "";
    /// <summary>
    ///Bin格式的Config的导出输出目录
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BinOutputDir {
      get { return binOutputDir_; }
      set {
        binOutputDir_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "JsonOutputDir" field.</summary>
    public const int JsonOutputDirFieldNumber = 4;
    private string jsonOutputDir_ = "";
    /// <summary>
    ///Json格式的Config的导出输出目录
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string JsonOutputDir {
      get { return jsonOutputDir_; }
      set {
        jsonOutputDir_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConfigSetting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConfigSetting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GenerateBatPath != other.GenerateBatPath) return false;
      if (CodeOutputDir != other.CodeOutputDir) return false;
      if (BinOutputDir != other.BinOutputDir) return false;
      if (JsonOutputDir != other.JsonOutputDir) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GenerateBatPath.Length != 0) hash ^= GenerateBatPath.GetHashCode();
      if (CodeOutputDir.Length != 0) hash ^= CodeOutputDir.GetHashCode();
      if (BinOutputDir.Length != 0) hash ^= BinOutputDir.GetHashCode();
      if (JsonOutputDir.Length != 0) hash ^= JsonOutputDir.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GenerateBatPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GenerateBatPath);
      }
      if (CodeOutputDir.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CodeOutputDir);
      }
      if (BinOutputDir.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BinOutputDir);
      }
      if (JsonOutputDir.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(JsonOutputDir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GenerateBatPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GenerateBatPath);
      }
      if (CodeOutputDir.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CodeOutputDir);
      }
      if (BinOutputDir.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BinOutputDir);
      }
      if (JsonOutputDir.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(JsonOutputDir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GenerateBatPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GenerateBatPath);
      }
      if (CodeOutputDir.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodeOutputDir);
      }
      if (BinOutputDir.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BinOutputDir);
      }
      if (JsonOutputDir.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JsonOutputDir);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConfigSetting other) {
      if (other == null) {
        return;
      }
      if (other.GenerateBatPath.Length != 0) {
        GenerateBatPath = other.GenerateBatPath;
      }
      if (other.CodeOutputDir.Length != 0) {
        CodeOutputDir = other.CodeOutputDir;
      }
      if (other.BinOutputDir.Length != 0) {
        BinOutputDir = other.BinOutputDir;
      }
      if (other.JsonOutputDir.Length != 0) {
        JsonOutputDir = other.JsonOutputDir;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            GenerateBatPath = input.ReadString();
            break;
          }
          case 18: {
            CodeOutputDir = input.ReadString();
            break;
          }
          case 26: {
            BinOutputDir = input.ReadString();
            break;
          }
          case 34: {
            JsonOutputDir = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            GenerateBatPath = input.ReadString();
            break;
          }
          case 18: {
            CodeOutputDir = input.ReadString();
            break;
          }
          case 26: {
            BinOutputDir = input.ReadString();
            break;
          }
          case 34: {
            JsonOutputDir = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
