
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class Reward
{
    private readonly System.Collections.Generic.Dictionary<int, RewardCfg> _dataMap;
    private readonly System.Collections.Generic.List<RewardCfg> _dataList;
    
    public Reward(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, RewardCfg>(n);
        _dataList = new System.Collections.Generic.List<RewardCfg>(n);
        for(int i = n ; i > 0 ; --i)
        {
            RewardCfg _v;
            _v = global::cfg.RewardCfg.DeserializeRewardCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Sn, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RewardCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<RewardCfg> DataList => _dataList;

    public RewardCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RewardCfg Get(int key) => _dataMap[key];
    public RewardCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

