
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class RewardCfg : Luban.BeanBase
{
    public RewardCfg(ByteBuf _buf) 
    {
        Sn = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Count = _buf.ReadInt();
    }

    public static RewardCfg DeserializeRewardCfg(ByteBuf _buf)
    {
        return new RewardCfg(_buf);
    }

    /// <summary>
    /// sn
    /// </summary>
    public readonly int Sn;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = -1128081771;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "sn:" + Sn + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

