
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public Reward Reward {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        Reward = new Reward(loader("reward"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Reward.ResolveRef(this);
    }
}

}
